language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master
