export const ner_tag_list = ['X','DTM_B','DTM_I','DES_B','DES_I','TTL_B','TTL_I','BRN_B','BRN_I','PER_B','PER_I','MEA_B','MEA_I','NUM_B','NUM_I','LOC_B','LOC_I','TRM_B','TRM_I','ORG_B','ORG_I','ABB_ORG_B','ABB_ORG_I','ABB_LOC_B','ABB_LOC_I','ABB_DES_B','ABB_DES_I','ABB_PER_B','ABB_PER_I','ABB_TTL_B','ABB_TTL_I','ABB_B','ABB_I','ABB','DDEM','NAME_B','__','O','UNK']

export const ner_des = {
    X:"ไม่ใช้",
    DTM_B:"Date/Time",
    DTM_I:"Date/Time",
    DES_B:"Designation",
    DES_I:"Designation",
    TTL_B:"Title",
    TTL_I:"Title",
    BRN_B:"Brand",
    BRN_I:"Brand",
    PER_B:"Person name",
    PER_I:"Person name",
    MEA_B:"Measurement",
    MEA_I:"Measurement",
    NUM_B:"Number",
    NUM_I:"Number",
    LOC_B:"Location",
    LOC_I:"Location",
    TRM_B:"Terminology",
    TRM_I:"Terminology",
    ORG_B:"Organization",
    ORG_I:"Organization",
    ABB_ORG_B:"Abbreviation of Organization",
    ABB_ORG_I:"Abbreviation of Organization",
    ABB_LOC_B:"Abbreviation of Location",
    ABB_LOC_I:"Abbreviation of Location",
    ABB_DES_B:"Abbreviation of Designation",
    ABB_DES_I:"Abbreviation of Designation",
    ABB_PER_B:"Abbreviation of Person name",
    ABB_PER_I:"Abbreviation of Person name",
    ABB_TTL_B:"Abbreviation of Title",
    ABB_TTL_I:"Abbreviation of Title",
    ABB_B:"Abbreviation",
    ABB_I:"Abbreviation",
    ABB:"แท็กerrorมาจากต้นฉบับเลย",
    DDEM:"แท็กerrorมาจากต้นฉบับเลย",
    NAME_B:"แท็กerrorมาจากต้นฉบับเลย",
    __:"แท็กerrorมาจากต้นฉบับเลย",
    O:"other",
    UNK:"ไม่ใช้",
}
